[project]
name = "python-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "protobuf>=6.33.0",
    "requests>=2.32.5",
    "websockets>=15.0.1",
]
